apiVersion: has.appstudio/v1alpha1
kind: HASComponent
metadata:
  name: petclinic-app-backend-45345
spec:
  componentName: backend
  application: petclinic-app-32453-asd345
  source:
    gitURL: https://github.com/devfile-samples/devfile-sample-python-basic
  resource:
    limits:
      CPU: 1M
      Memory: 1Gi
  replicas: 3
  route: myapplication.someurl.com
  port: 8080
  env:
    - key: SOME_ENV
      value: test-value