apiVersion: has.appstudio/v1alpha1
kind: HASApplication
metadata:
 name: petclinic-app-32453-asd345
spec:
  displayName: "Petclinic App"
  appModelRepository: 
    url: https://github.com/johnmcollier/petclinic-app
    version: 
    context: 
  gitOpsRepository: 
    url: https://github.com/johnmcollier/petclinic-gitops
    version:
    context:
  description: “application definition for petclinic-app”