apiVersion: has.appstudio/v1alpha1
kind: HASApplication
metadata:
 name: petclinic-app-32453-asd345
spec:
  displayName: "Petclinic App"
  gitRepo: https://github.com/johnmcollier/petclinic-app
  description: “application definition for petclinic-app”