apiVersion: has.appstudio/v1alpha1
kind: HASApplication
metadata:
 name: petclinic-app-32453-asd345
spec:
  displayName: "Petclinic App"
  sourceRepository: https://github.com/johnmcollier/petclinic-app
  gitOpsRepository: https://github.com/johnmcollier/petclinic-gitops
  description: “application definition for petclinic-app”
status:
  conditions:
  - lastTransitionTime: "2022-01-22T16:29:31Z"
    status: "True"
    type: Created
  devfile:
    schemaVersion: 2.1.0
    metadata:
    name: petclinic-app
    attributes:
      has.description: "application definition for petclinic-app"
      has.identifier: "com.redhat.has"
      has.version: "has/v1"
      sourceRepo: 'https://github.com/johnmcollier/petclinic-app'
      gitOpsRepo: 'https://github.com/johnmcollier/petclinic-gitops'
